-- CreateTable
CREATE TABLE `items` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `LABEL` VARCHAR(255) NULL,
    `DESCRIPTION` VARCHAR(255) NULL,
    `QUANTITY` INTEGER NULL,
    `MINIMUM_STOCK` INTEGER NOT NULL DEFAULT 1,
    `STOCK_ID` INTEGER NULL,

    INDEX `STOCK_ID`(`STOCK_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `stocks` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `LABEL` VARCHAR(255) NOT NULL,
    `DESCRIPTION` VARCHAR(255) NULL,
    `CATEGORY` ENUM('alimentation', 'hygiene', 'artistique') NOT NULL DEFAULT 'alimentation',
    `USER_ID` INTEGER NULL,

    INDEX `stocks_ibfk_1`(`USER_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `users` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `EMAIL` VARCHAR(255) NOT NULL,

    UNIQUE INDEX `unique_email`(`EMAIL`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `items` ADD CONSTRAINT `items_ibfk_1` FOREIGN KEY (`STOCK_ID`) REFERENCES `stocks`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `stocks` ADD CONSTRAINT `stocks_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `users`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
